import { db, examTopics } from "../db";

const sampleTopics = [
  {
    examRound: 137,
    questionNumber: 1,
    title: "Zero Trust Architecture",
    description: "제로 트러스트 보안 모델의 개념, 원칙, 구현 방안에 대해 설명하시오.",
    category: "정보보안",
    tags: ["보안", "네트워크", "인증", "Zero Trust", "ZTNA"],
    difficulty: 4,
    year: 2024,
    season: "fall",
    frequency: 3,
    relatedTopics: [],
  },
  {
    examRound: 137,
    questionNumber: 2,
    title: "Kubernetes Service Mesh",
    description: "쿠버네티스 환경에서 서비스 메시의 역할과 구현 방안에 대해 설명하시오.",
    category: "정보시스템구축관리",
    tags: ["클라우드", "컨테이너", "MSA", "Istio", "Linkerd"],
    difficulty: 5,
    year: 2024,
    season: "fall",
    frequency: 2,
    relatedTopics: [],
  },
  {
    examRound: 137,
    questionNumber: 3,
    title: "MLOps (Machine Learning Operations)",
    description: "MLOps의 개념과 머신러닝 모델의 생명주기 관리 방안에 대해 설명하시오.",
    category: "최신기술",
    tags: ["AI/ML", "DevOps", "자동화", "모델관리"],
    difficulty: 4,
    year: 2024,
    season: "fall",
    frequency: 1,
    relatedTopics: [],
  },
  {
    examRound: 136,
    questionNumber: 1,
    title: "OAuth 2.0 Grant Types",
    description: "OAuth 2.0의 다양한 인증 방식(Grant Types)과 각각의 사용 사례 및 보안 고려사항에 대해 설명하시오.",
    category: "정보보안",
    tags: ["인증", "보안", "API", "OAuth", "토큰"],
    difficulty: 3,
    year: 2024,
    season: "spring",
    frequency: 5,
    relatedTopics: [],
  },
  {
    examRound: 136,
    questionNumber: 2,
    title: "Event-Driven Architecture",
    description: "이벤트 주도 아키텍처의 개념, 구성 요소, 장단점에 대해 설명하시오.",
    category: "정보시스템구축관리",
    tags: ["아키텍처", "이벤트", "비동기", "메시징"],
    difficulty: 4,
    year: 2024,
    season: "spring",
    frequency: 3,
    relatedTopics: [],
  },
  {
    examRound: 136,
    questionNumber: 3,
    title: "Database Sharding",
    description: "대용량 데이터베이스의 샤딩 전략과 구현 시 고려사항에 대해 설명하시오.",
    category: "데이터베이스",
    tags: ["데이터베이스", "확장성", "분산", "파티셔닝"],
    difficulty: 4,
    year: 2024,
    season: "spring",
    frequency: 4,
    relatedTopics: [],
  },
  {
    examRound: 136,
    questionNumber: 4,
    title: "CI/CD Pipeline",
    description: "지속적 통합/배포 파이프라인의 구성 요소와 모범 사례에 대해 설명하시오.",
    category: "소프트웨어공학",
    tags: ["DevOps", "자동화", "배포", "Jenkins", "GitLab"],
    difficulty: 3,
    year: 2024,
    season: "spring",
    frequency: 6,
    relatedTopics: [],
  },
  {
    examRound: 135,
    questionNumber: 1,
    title: "SBOM (Software Bill of Materials)",
    description: "소프트웨어 공급망 보안을 위한 SBOM의 개념과 활용 방안에 대해 설명하시오.",
    category: "정보보안",
    tags: ["보안", "공급망", "취약점", "오픈소스"],
    difficulty: 4,
    year: 2023,
    season: "fall",
    frequency: 2,
    relatedTopics: [],
  },
  {
    examRound: 135,
    questionNumber: 2,
    title: "API Gateway Pattern",
    description: "마이크로서비스 아키텍처에서 API Gateway의 역할과 구현 방안에 대해 설명하시오.",
    category: "정보시스템구축관리",
    tags: ["아키텍처", "MSA", "API", "Gateway"],
    difficulty: 3,
    year: 2023,
    season: "fall",
    frequency: 6,
    relatedTopics: [],
  },
  {
    examRound: 135,
    questionNumber: 3,
    title: "Container Orchestration",
    description: "컨테이너 오케스트레이션의 개념과 Kubernetes의 주요 기능에 대해 설명하시오.",
    category: "정보시스템구축관리",
    tags: ["컨테이너", "Kubernetes", "오케스트레이션", "클라우드"],
    difficulty: 4,
    year: 2023,
    season: "fall",
    frequency: 5,
    relatedTopics: [],
  },
  {
    examRound: 135,
    questionNumber: 4,
    title: "GraphQL",
    description: "GraphQL의 개념, REST API와의 차이점, 장단점에 대해 설명하시오.",
    category: "소프트웨어공학",
    tags: ["API", "GraphQL", "REST", "쿼리"],
    difficulty: 3,
    year: 2023,
    season: "fall",
    frequency: 2,
    relatedTopics: [],
  },
  {
    examRound: 134,
    questionNumber: 1,
    title: "Blockchain Consensus Algorithm",
    description: "블록체인의 합의 알고리즘(PoW, PoS 등)에 대해 설명하시오.",
    category: "최신기술",
    tags: ["블록체인", "합의알고리즘", "PoW", "PoS"],
    difficulty: 5,
    year: 2023,
    season: "spring",
    frequency: 3,
    relatedTopics: [],
  },
  {
    examRound: 134,
    questionNumber: 2,
    title: "Edge Computing",
    description: "엣지 컴퓨팅의 개념, 클라우드 컴퓨팅과의 차이, 활용 사례에 대해 설명하시오.",
    category: "최신기술",
    tags: ["엣지컴퓨팅", "클라우드", "IoT", "5G"],
    difficulty: 4,
    year: 2023,
    season: "spring",
    frequency: 2,
    relatedTopics: [],
  },
  {
    examRound: 134,
    questionNumber: 3,
    title: "Domain-Driven Design (DDD)",
    description: "도메인 주도 설계의 핵심 개념과 구현 패턴에 대해 설명하시오.",
    category: "소프트웨어공학",
    tags: ["DDD", "설계", "아키텍처", "도메인"],
    difficulty: 5,
    year: 2023,
    season: "spring",
    frequency: 4,
    relatedTopics: [],
  },
  {
    examRound: 134,
    questionNumber: 4,
    title: "Serverless Architecture",
    description: "서버리스 아키텍처의 개념, 특징, 적용 사례에 대해 설명하시오.",
    category: "정보시스템구축관리",
    tags: ["서버리스", "클라우드", "FaaS", "Lambda"],
    difficulty: 3,
    year: 2023,
    season: "spring",
    frequency: 5,
    relatedTopics: [],
  },
];

async function seedTopics() {
  try {
    console.log("Starting to seed exam topics...");

    // Insert all topics
    const result = await db.insert(examTopics).values(sampleTopics).returning();

    console.log(`Successfully inserted ${result.length} topics`);
    console.log("Sample topics:");
    result.forEach((topic) => {
      console.log(`- [${topic.examRound}회 #${topic.questionNumber}] ${topic.title}`);
    });

    process.exit(0);
  } catch (error) {
    console.error("Error seeding topics:", error);
    process.exit(1);
  }
}

seedTopics();
